spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:jpadb
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      show-sql: false

logging:
  level:
    root: 'info'
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql: trace
    org.springframework.jdbc.core.JdbcTemplate: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace


